[green_agent]
agentbeats_id = ""
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "network_operator"
env = {}

[[participants]]
agentbeats_id = ""
name = "role_2_name"
env = {}

[config]
prompt_type = "zeroshot_base" 
num_queries = 1 
complexity_level = ["level1", "level2"]
output_dir = "output" 
output_file = "query_output.jsonl" 
benchmark_path = "assessment_queries.jsonl" 