[green_agent]
agentbeats_id = ""
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
role = "network_operator"
agentbeats_id = ""
env = {}

[config]
prompt_type = "zeroshot_base"
num_queries = 1
benchmark_path = "assessment_error_config.json"
regenerate_benchmark = false
output_dir = "output"
max_iterations = 10
num_switches = 2
num_hosts_per_subnet = 1
