name: Run MALT Evaluation

on:
  push:
    paths:
      - 'malt_scenario.toml'

jobs:
  run-malt:
    if: github.event.repository.fork == true || github.ref != 'refs/heads/main'
    permissions:
      contents: write
      packages: read

    uses: ./.github/workflows/run-scenario.yml
    secrets: inherit
    with:
      scenario-file: 'malt_scenario.toml'
      benchmark-app: 'malt'